### ISSUE TITLE
子のコンポーネントの状態が更新されたら親コンポーネントの状態も更新したい

### ISSUE THREAD

**Issue by punipuni21** [yusuke-suehiro/Mahjong-PointsCalc#11]
@yusuke-suehiro 

何かいい方法知ってますか？

**Comment by yusuke-suehiro** [comment]
状態を更新というのはパラメータを渡すという意味ですか？
コンポーネント間のパラメータの受け渡しは以下の記事を参考にするとできるかもしれません．
実装したことないので分かりませんが．

https://qiita.com/kyoshidajp/items/0ddb156d96bb6337f623

**Comment by punipuni21** [comment]
なるほど，やはりコールバック関数を使うようですね．．．
ここら辺よく分からないので勉強してみます

**Comment by punipuni21** [comment]
解決したので閉じます
