### ISSUE TITLE
php artisan migrateがエラーを吐く件について

### ISSUE THREAD

**Issue by punipuni21** [yusuke-suehiro/Mahjong-PointsCalc#5]
@yusuke-suehiro 
php artisan migrateの前にデータベース関連で準備することはありますか？

現状Connection refusedになります

**Comment by yusuke-suehiro** [comment]
ローカルにデータベースを作る
create database hogehoge
envファイルにデータベースの名前とデータベースの種類を入力

これでダメならまた教えてください

**Comment by punipuni21** [comment]
https://qiita.com/kazu_wsx/items/bb787e9e4e919da03705

この記事で改善しました．

**Comment by punipuni21** [comment]
https://www.autovice.jp/articles/60

**Comment by yusuke-suehiro** [comment]
あーなるほど
MySQL側の問題だったんですね
勉強になります

**Comment by punipuni21** [comment]
https://yaba-blog.com/laravel-db/
https://qiita.com/KenjiOtsuka/items/8e520f53df2ae84f75e9

どうもsqlの認証周りのcaching_sha2_passwordにPHPが対応してないらしく，MySQL側の設定を変更しないといけなかったようです．これを修正したら動きました．

**Comment by punipuni21** [comment]
解決したのでこのissueは閉じます
