### ISSUE TITLE
Reactコンポーネントが大文字始まり出ないとブラウザ上でReactコンポーネントとして認識されない件について

### ISSUE THREAD

**Issue by punipuni21** [yusuke-suehiro/Mahjong-PointsCalc#7]
@yusuke-suehiro 
- ユーザ定義のReactコンポーネントは大文字始まり出ないとHTMLタグとみなされるらしいので今後作成する際は大文字始まりでお願いします
- 参考：https://reactjs.org/docs/jsx-in-depth.html#user-defined-components-must-be-capitalized

**Comment by yusuke-suehiro** [comment]
了解です．
